apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: gcp-lornu-ai
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterName: stevedores-cluster
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets-system
