---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: crossplane-heaven
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/stevedores-org/crossplane-heaven
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-crossplane
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/crossplane/install
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane-heaven
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-eso
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/eso/install
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane-heaven
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-providers
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-crossplane
  interval: 10m0s
  path: ./infrastructure/crossplane/providers
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane-heaven
