apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: crossplane-heaven
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/stevedores-org/crossplane-heaven
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-crossplane
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/crossplane/install
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane-heaven
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-eso
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/eso/install
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane-heaven
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-providers
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/crossplane/providers/gcp/provider
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane-heaven
  dependsOn:
    - name: infrastructure-crossplane
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-provider-configs
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/crossplane/providers/gcp/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane-heaven
  dependsOn:
    - name: infrastructure-providers
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-gcp-definitions
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/gcp/compositions
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane-heaven
  dependsOn:
    - name: infrastructure-provider-configs
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-gcp-claims
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/gcp/claims
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane-heaven
  dependsOn:
    - name: infrastructure-gcp-definitions
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-storage
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/storage
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane-heaven
  dependsOn:
    - name: infrastructure-gcp-claims
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-apps
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane-heaven
  dependsOn:
    - name: infrastructure-storage
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cert-manager
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane-heaven
  dependsOn:
    - name: infrastructure-apps
