apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxidizedgraph
  namespace: default
  labels:
    app: oxidizedgraph
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oxidizedgraph
  template:
    metadata:
      labels:
        app: oxidizedgraph
    spec:
      containers:
        - name: oxidizedgraph
          image: >-
            us-central1-docker.pkg.dev/gcp-lornu-ai/cloud-run-source-deploy/oxidizedgraph:latest
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          env:
            - name: RUST_LOG
              value: info
            - name: PORT
              value: "8080"
            - name: STORAGE_PATH
              value: /app/data
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: oxidizedgraph-data
---
apiVersion: v1
kind: Service
metadata:
  name: oxidizedgraph-service
  namespace: default
  labels:
    app: oxidizedgraph
spec:
  selector:
    app: oxidizedgraph
  ports:
    - port: 80
      targetPort: 8080
      name: http
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxidizedrag
  namespace: default
  labels:
    app: oxidizedrag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oxidizedrag
  template:
    metadata:
      labels:
        app: oxidizedrag
    spec:
      containers:
        - name: oxidizedrag
          image: >-
            us-central1-docker.pkg.dev/gcp-lornu-ai/cloud-run-source-deploy/oxidizedrag:latest
          ports:
            - containerPort: 8081
              name: http
          resources:
            requests: {}
          env:
            - name: RUST_LOG
              value: debug
            - name: DB_PATH
              value: /app/db
            - name: EMBEDDING_BACKEND
              value: huggingface
          volumeMounts:
            - name: data
              mountPath: /app/db
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: oxidizedrag-db
---
apiVersion: v1
kind: Service
metadata:
  name: oxidizedrag-service
  namespace: default
  labels:
    app: oxidizedrag
spec:
  selector:
    app: oxidizedrag
  ports:
    - port: 80
      targetPort: 8081
      name: http
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stevedores-org
  namespace: default
  labels:
    app: stevedores-org
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stevedores-org
  template:
    metadata:
      labels:
        app: stevedores-org
    spec:
      containers:
        - name: stevedores-org
          image: >-
            us-central1-docker.pkg.dev/gcp-lornu-ai/cloud-run-source-deploy/stevedores-org:latest
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests: {}
          env:
            - name: PORT
              value: '8080'
          volumeMounts: []
      volumes: []
---
apiVersion: v1
kind: Service
metadata:
  name: stevedores-org-service
  namespace: default
  labels:
    app: stevedores-org
spec:
  selector:
    app: stevedores-org
  ports:
    - port: 80
      targetPort: 8080
      name: http
  type: ClusterIP
